LABEL ROCKNIX
  LINUX /KERNEL
  FDTDIR /
  ## FDT: don't forget the leading slash, remove all symbols after .dtb (including whitespace)
  # FDT /your-custom-devicetree.dtb
  FDTOVERLAYS /overlays/mipi-panel.dtbo
  APPEND boot=${partition_boot} disk=${partition_storage} @EXTRA_CMDLINE@ uboot.hwid_adc=${hwid_adc}
